dist: xenial
language: python
python:
  - 3.7.3
before_install:
  - chmod +x manage.py
install:
  - pip install -r requirements.txt
script:
  - SECRET_KEY="whateverwillbewillbe" DEV="1" python manage.py test