# Generated by Django 2.2.6 on 2019-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
