# Generated by Django 2.2.6 on 2019-10-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191022_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='town',
            new_name='town_or_city',
        ),
    ]
