
// obfusicated code generated by https://obfuscator.io/ to hide key

var _0x19e0 = ['cGtfdGVzdF9IQklSTERPTXFURmN1UlpXeFI0QmpzTmYwMGE5M200aWQz'];
(function (_0x989966, _0xdfe4fd) {
    var _0x1221e3 = function (_0x2223a1) {
        while (--_0x2223a1) {
            _0x989966['push'](_0x989966['shift']());
        }
    };
    _0x1221e3(++_0xdfe4fd);
}(_0x19e0, 0x97));
var _0x397c = function (_0x3b5c12, _0x7daf6) {
    _0x3b5c12 = _0x3b5c12 - 0x0;
    var _0x2f8cfc = _0x19e0[_0x3b5c12];
    if (_0x397c['wIwqyg'] === undefined) {
        (function () {
            var _0x38ef8c = function () {
                var _0x34d236;
                try {
                    _0x34d236 = Function('return\x20(function()\x20' +
                        '{}.constructor(\x22return\x20this\x22)(\x20)' + ');')();
                } catch (_0x4b0c1e) {
                    _0x34d236 = window;
                }
                return _0x34d236;
            };
            var _0x57e1e1 = _0x38ef8c();
            var _0x3e4e0a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
            _0x57e1e1['atob'] || (_0x57e1e1['atob'] = function (_0x5d49a7) {
                var _0x1b64ce = String(_0x5d49a7)['replace'](/=+$/, '');
                for (var _0x3d5488 = 0x0, _0x277101, _0x6c2a0d, _0x3aff3f = 0x0, _0x55babe =
                    ''; _0x6c2a0d = _0x1b64ce['charAt'](_0x3aff3f++); ~_0x6c2a0d && (_0x277101 =
                        _0x3d5488 % 0x4 ? _0x277101 * 0x40 + _0x6c2a0d : _0x6c2a0d, _0x3d5488++
                        % 0x4) ? _0x55babe += String['fromCharCode'](0xff & _0x277101 >> (-0x2 *
                        _0x3d5488 & 0x6)) : 0x0) {
                    _0x6c2a0d = _0x3e4e0a['indexOf'](_0x6c2a0d);
                }
                return _0x55babe;
            });
        }());
        _0x397c['tRXelq'] = function (_0x4170f2) {
            var _0x148754 = atob(_0x4170f2);
            var _0x391611 = [];
            for (var _0x3b7e19 = 0x0, _0x440374 = _0x148754['length']; _0x3b7e19 <
                _0x440374; _0x3b7e19++) {
                _0x391611 += '%' + ('00' + _0x148754['charCodeAt'](_0x3b7e19)['toString'](0x10))[
                    'slice'](-0x2);
            }
            return decodeURIComponent(_0x391611);
        };
        _0x397c['bclYEs'] = {};
        _0x397c['wIwqyg'] = !![];
    }
    var _0x19d703 = _0x397c['bclYEs'][_0x3b5c12];
    if (_0x19d703 === undefined) {
        _0x2f8cfc = _0x397c['tRXelq'](_0x2f8cfc);
        _0x397c['bclYEs'][_0x3b5c12] = _0x2f8cfc;
    } else {
        _0x2f8cfc = _0x19d703;
    }
    return _0x2f8cfc;
};

function returnStripePublishableKey() {
    return _0x397c('0x0');
}