# Generated by Django 2.2.6 on 2019-11-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdestination',
            name='shipping_time',
            field=models.CharField(default='1 to 2 weeks', max_length=150),
        ),
    ]
