# Generated by Django 2.2.6 on 2019-10-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191025_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.Destination_country'),
        ),
    ]
