# Generated by Django 2.2.6 on 2019-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_nl', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_eu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_non_eu', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
