# Generated by Django 2.2.6 on 2019-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_destination_country_shipping_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_category',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=6),
            preserve_default=False,
        ),
    ]
