# Generated by Django 2.2.6 on 2019-10-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_profile',
        ),
    ]
