# Generated by Django 2.2.6 on 2019-10-11 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191011_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_listed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
