# Generated by Django 2.2.6 on 2019-10-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_date_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_listed',
            field=models.DateField(default='today'),
        ),
    ]
