# Generated by Django 2.2.6 on 2019-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191014_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
