# Generated by Django 2.2.6 on 2019-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', max_length=160),
        ),
    ]
