# Generated by Django 2.2.6 on 2019-10-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WM', 'Weird & Misc'), ('SW', 'Star Wars'), ('OC', 'Special Occasions'), ('JH', 'Jobs & Hobbies'), ('HP', 'Harry Potter'), ('FA', 'Famous'), ('DW', 'Doctor Who'), ('HW', 'Halloween'), ('CM', 'Christmas')], default='SW', max_length=3),
        ),
    ]
