# Generated by Django 2.2.6 on 2019-10-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_tag',
        ),
    ]
