# Generated by Django 2.2.6 on 2019-10-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20191017_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Weird & Misc', 'Weird & Misc'), ('Star Wars', 'Star Wars'), ('Special Occasions', 'Special Occasions'), ('Jobs & Hobbies', 'Jobs & Hobbies'), ('Harry Potter', 'Harry Potter'), ('Famous', 'Famous'), ('Doctor Who', 'Doctor Who'), ('Halloween', 'Halloween'), ('Christmas', 'Christmas')], default='Star Wars', max_length=3),
        ),
    ]
