# Generated by Django 2.2.6 on 2019-10-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20191022_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='product_image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='product_image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='product_image3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image4',
            new_name='product_image4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image5',
            new_name='product_image5',
        ),
    ]
