# Generated by Django 2.2.6 on 2019-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20191023_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image5',
            field=models.ImageField(blank=True, default='Packaging.jpg', null=True, upload_to='product_images'),
        ),
    ]
